spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t6c5FzR3umWd8aUvChj
      secret-key: oHkVaJLXBHvZMF5mNNi5DZr3mNdjvH
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-three220802
  application:
    name: gulimall-third-party

server:
  port: 30000