server:
  port: 20000
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.10.100
    port: 6379